// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLiGPQT_GAGPHJ-I-1-RiiPivt6RWYQTw',
    appId: '1:757598541562:web:f742b5fb5aa5ad77cd9b43',
    messagingSenderId: '757598541562',
    projectId: 'dailynews-94c28',
    authDomain: 'dailynews-94c28.firebaseapp.com',
    storageBucket: 'dailynews-94c28.firebasestorage.app',
    measurementId: 'G-HTFRD6H2H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFxFCnk0DHHVz025jlgAg-tdWBATl3HTc',
    appId: '1:757598541562:android:550eafb2bb24d212cd9b43',
    messagingSenderId: '757598541562',
    projectId: 'dailynews-94c28',
    storageBucket: 'dailynews-94c28.firebasestorage.app',
  );
}
